export enum PrismaErrorCode {
    UNIQUE_CONSTRAINT = "P2002",
    FOREIGN_KEY_CONSTRAINT = "P2003",
    CONSTRAINT_FAILED = "P2004",
    REQUIRED_FIELD_NULL = "P2011",
    REQUIRED_FIELD_MISSING = "P2012",
    REQUIRED_RELATION_VIOLATION = "P2014",
    RECORD_NOT_FOUND = "P2025"
}